### ISSUE TITLE
Dead link on developer-portal-starter/developer-portal/redoc-integration.md page

### ISSUE THREAD

**Issue by WaterSibilantFalling** [Redocly/developer-portal-starter#107]
On this page

https://github.com/Redocly/developer-portal-starter/blob/8622c77f37a2cc7c58032c31a2cb5a5799722377/developer-portal/redoc-integration.md

This link 

https://github.com/Redocly/developer-portal-starter/blob/resources/multi-file-definitions.md 

is dead

**Comment by RomanHotsiy** [comment]
This has been resolved on the latest version already.
