### ISSUE TITLE
Table Of Contents .mdx files

### ISSUE THREAD

**Issue by MarcoDeJong** [Redocly/developer-portal-starter#13]
When using a `.md` file and having either Table Of Contents enabled in `siteConfig.yaml` or via Front Matter, I see a nice Table Of Contents autogenerated from all headers of the page. :)

When renaming the same file to a `.mdx` file, so I can use components, then suddenly the Table Of Contents dissappears. 

As a user it looks like this is a bug. As a developer it might be a feature ;)

**Comment by RomanHotsiy** [comment]
@MarcoDeJong Definitely not a feature 😄 

Table Of Contents is not yet supported for MDX components. We expect to have it fixed next week.

**Comment by MarcoDeJong** [comment]
Great work guys!

**Comment by RomanHotsiy** [comment]
@MarcoDeJong an update on the ToC for MDX. It's not implemented yet as we faced one limitation. It is in progress.
Fortunately, we should have it done for the next release.

Sorry for the delay.

**Comment by MarcoDeJong** [comment]
No rush. Thanks for your update anyway!

**Comment by spacedsweden** [comment]
hey, one more thing on this.
because you don't have the TOC in mdx, the content also get jumpy 

https://sinch.redoc.ly/docs/sms/
https://sinch.redoc.ly/docs/sms/messages/

Because it seems like the content container gets centered instead of being right aligned.

**Comment by spacedsweden** [comment]
i would like to upvote both the above if I could vote :D

**Comment by MarcoDeJong** [comment]
> hey, one more thing on this.
> because you don't have the TOC in mdx, the content also get jumpy
> 
> https://sinch.redoc.ly/docs/sms/
> https://sinch.redoc.ly/docs/sms/messages/
> 
> Because it seems like the content container gets centered instead of being right aligned.

Correct. I see the same in our portal.

**Comment by MarcoDeJong** [comment]
Did you guys happen to find a way to fix this? :)

**Comment by adamaltman** [comment]
Yes, this is solved in `1.1.0-beta.52`.
