### ISSUE TITLE
How do you style the button(s) in the documentation section?

### ISSUE THREAD

**Issue by KasraTabrizi** [Redocly/developer-portal-starter#17]
Hello,

I would like to know how to change the styling of the buttons generated in the documentation section of the portal. See screenshot below(red arrow):

![Annotation 2020-07-15 100406](https://user-images.githubusercontent.com/36457522/87648130-f382c980-c74f-11ea-9790-389f5b64d0dc.png)

I have tried to style it through the theme.ts file, but it is quite limited. I can change the primary color but then the background color of the navbar and footer is changed as well.
Is there a way to style it or a way to create a custom React component that can overwrite this button?

Thanks in advance.

Greetings,

Kasra Tabrizi

**Comment by RomanHotsiy** [comment]
@KasraTabrizi you can't override this button right now. Let me know what styles you want to override and I will if we can add corresponding theme settings.
Also, we will be able to allow overriding this button using custom component.

**Comment by KasraTabrizi** [comment]
@RomanHotsiy 
For this particular button, I want to be able to style the text color, border-radius, border-color, font-family. I would also like to add a hover animation where the background color changes.
If is it too much to implement, I can indeed just write a custom component. But then the right props needs to be passed, like the location to which it should go when you press on that button, the text of the button depending to which section you are, etc.

**Comment by RomanHotsiy** [comment]
@KasraTabrizi considering you need hover effect I would recommend going with custom component approach. Unfortunately, there is no easy way to override this button ATM. We aim to have it in the next release next week. It can be postponed for another week though.

**Comment by KasraTabrizi** [comment]
@RomanHotsiy 

Ok, thanks!

**Comment by adamaltman** [comment]
This can be done now in the `theme.ts` in the 1.1.x release range which includes reference 2.x.

![image](https://user-images.githubusercontent.com/1161871/134822872-383c846f-0f74-486a-b72f-bc0d31ce22bf.png)

Read more inside of the **components > buttons** section:

https://redoc.ly/docs/developer-portal/configuration/theme/
