### ISSUE TITLE
Feature Request: Allow the API Info section to be hidden

### ISSUE THREAD

**Issue by akshay-8d66** [Redocly/developer-portal-starter#179]
This is the same request from earlier, from the API Reference Product - https://github.com/Redocly/redoc/issues/942

**Comment by RomanHotsiy** [comment]
@akshay-8d66 this should be possible by putting `hideInfoSection: true` into settings section of corresponding .page.yaml file.

Please, confirm.

**Comment by akshay-8d66** [comment]
Thanks, that works!
