### ISSUE TITLE
Sidebar styling issue

### ISSUE THREAD

**Issue by KasraTabrizi** [Redocly/developer-portal-starter#18]
Hey everyone,

I have a problem styling the sidebar of the portal. I can only style the backgroundColor and the width (see code snippet in **theme.ts**)
```
sidebar: {
    backgroundColor: '#fafafa',
    width: '260px',
  },
```
However, I would like to style the text color, border radius, background color when hovering. Adding those properties doesn't seem to do anything. I did a bit of a digging in the **redoc/typings/utils/theme.d.ts** where I found the following:

```
    sidebar: {
        width: string;
        backgroundColor: string;
        textColor: string;
        activeTextColor: string;
        groupItems: {
            textTransform: string;
        };
        level1Items: {
            textTransform: string;
        };
        arrow: {
            size: string;
            color: string;
        };
    };
```

I tried adding a textColor and arrow property to my theme.ts file but nothing happened to the styling.
Is there a way to add extra properties to the theme.ts or do I also have to override the whole sidebar nav?

Thanks in advance,

Greetings,

Kasra Tabrizi

**Comment by adamaltman** [comment]
We can add extra theme toggles.

**Comment by RomanHotsiy** [comment]
@KasraTabrizi we will add extra toggles in the next release early next week.

**Comment by KasraTabrizi** [comment]
@adamaltman and @RomanHotsiy 

Thanks!

**Comment by RomanHotsiy** [comment]
We've added a few extra knobs in beta.84:

`sidebar.textColor`
`sidebar.activeTextColor`
`sidebar.activeBgColor`

**Comment by RomanHotsiy** [comment]
Sorry for the huge delay with this 🙈 .

We'll update docs and changelog later this week.
