### ISSUE TITLE
Selecting API method cuts off page header

### ISSUE THREAD

**Issue by Hopp3r** [Redocly/developer-portal-starter#183]
Selecting a given method from the API menu will open that method's page content but cut off the header (the page will be scrolled down slightly). 
Re-clicking the menu item will load the page correctly.
I've tested this with version "1.1.0-beta.80".

https://user-images.githubusercontent.com/12385709/153523604-1765055e-ee2d-443a-b622-c936d9e899a8.mp4

**Comment by RomanHotsiy** [comment]
This should be resolved in the beta.81 today. This was a regression.
