### ISSUE TITLE
Diagram/Code Block Titles

### ISSUE THREAD

**Issue by JeroenVanHautte** [Redocly/developer-portal-starter#19]
Currently, if you put several mermaid diagrams under each other, each of them gets the "mermaid" as a title. Would it be possible to add an optional parameter to set the title for a block of code? In that case, it would be possible to neatly show multiple diagrams in the same place.

![image](https://user-images.githubusercontent.com/11805125/88312383-5d800d80-cd12-11ea-9a81-9da1e477b0ba.png)

**Comment by adamaltman** [comment]
This is in our roadmap. We're deciding on the syntax, such as: 

> ` ```mermaid!Title here`

**Comment by RomanHotsiy** [comment]
@JeroenVanHautte upgrade to beta.71 and use the following syntax:

~~~
```mermaid Title Here
# diagram code here
```

```mermaid Other Title Here
# diagram code here
```
~~~
