### ISSUE TITLE
Upgrade MermaidJS to 8.6.0 & allow for directives

### ISSUE THREAD

**Issue by JeroenVanHautte** [Redocly/developer-portal-starter#20]
Sequence diagrams in mermaid 8.6 ([https://mermaid-js.github.io/mermaid/#/8.6.0_docs](https://mermaid-js.github.io/mermaid/#/8.6.0_docs)) support auto wrapping & newlines, neither of which are currently supported inside the developer portal. Would it be possible to upgrade this system, as to allow for more flexibility per diagram?

**Comment by RomanHotsiy** [comment]
It's available in beta.71.
