### ISSUE TITLE
Allow for the use of local CSS stylesheets

### ISSUE THREAD

**Issue by JeroenVanHautte** [Redocly/developer-portal-starter#21]
Currently, a local path included as a style sheet in the stylesheets part of siteConfig.yaml results in an error, making it hard to include custom CSS through this option without workarounds. Another option would be to allow for full css customisation options through theme.ts, instead of only the options selected beforehand.

Thanks!

**Comment by JeroenVanHautte** [comment]
Current workaround is including a css-override.js script in the siteConfig:
```
// Get HTML head element 
var head = document.getElementsByTagName('HEAD')[0];  

// Create new link Element 
var style = document.createElement('style'); 
style.innerHTML = `
article p a {
    color: 'hotpink'; 
  }
`

// Append link element to HTML head 
head.appendChild(style);  
```

**Comment by RomanHotsiy** [comment]
@JeroenVanHautte

> a local path included as a style sheet in the stylesheets part of siteConfig.yaml results in an error

Could you provide more details? What errors do you see? It should work with local files.

**Comment by JeroenVanHautte** [comment]
> @JeroenVanHautte
> 
> > a local path included as a style sheet in the stylesheets part of siteConfig.yaml results in an error
> 
> Could you provide more details? What errors do you see? It should work with local files.

When I provide a local path, it seems any slashes are removed from it before it is evaluated - e.g. C:/temp/style.css would become C:tempstyle.css (except we use a relative path of course) - the build process just fails before it shows the portal due to this. @RomanHotsiy Have you tried using a css file from your static folder?

**Comment by RomanHotsiy** [comment]
@JeroenVanHautte can you try providing path with Linux-style slashes `\`. And provide a relative path, not the absolute.

**Comment by JeroenVanHautte** [comment]
Hi @RomanHotsiy, i'm afraid the problem persists - I am using a relative path, but this gets converted into an absolute path during the build process it seems - here's the error:

Generating development JavaScript bundle failed

Can't resolve 'C:<PATH_TO_PROJECT_HERE>developer-portalstaticcss-override.css' in 'C:<PATH_TO_PROJECT_HERE>developer-portal\node_modules
\@redocly\developer-portal\dist\engine\gatsby'

Just want to add that local (relative) paths do work fine for the scripts option.

**Comment by RomanHotsiy** [comment]
@JeroenVanHautte must be some issue. I will check it out.
Thanks for reporting.

Will keep you posted.

**Comment by RomanHotsiy** [comment]
Hey @JeroenVanHautte,

Should be fixed on `beta.71`. Could you please upgrade and verify?

**Comment by RomanHotsiy** [comment]
ping @JeroenVanHautte

**Comment by adamaltman** [comment]
I'm closing this one as solved. If it isn't @JeroenVanHautte please re-open it.
