### ISSUE TITLE
Cannot find module '@redocly/ui'

### ISSUE THREAD

**Issue by wehub** [Redocly/developer-portal-starter#214]
I'm using Visual Studio Code and this error message is triggering my error OCD.
The code works but why am I getting this message?

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/22106535/171491067-9f71830f-4696-4b6e-93cf-8cefa0308af6.png">

**Comment by RomanHotsiy** [comment]
Please, update `@redocly/ui` to `@redocly/developer-portal/ui`. It should resolve the issue.

This is just legacy code.

**Comment by wehub** [comment]
Thank you.

**Comment by wehub** [comment]
I am also seeing this note in VSCode:
![image](https://user-images.githubusercontent.com/22106535/171734042-3c02e3bc-83a9-4ae2-af65-b200aa44c7e9.png)

Is the suggested correction appropriate.

**Comment by RomanHotsiy** [comment]
I think it is.

**Comment by RomanHotsiy** [comment]
I think it is.
