### ISSUE TITLE
Mermaid Arrowheads Disappear When Using Multiple Diagrams

### ISSUE THREAD

**Issue by JeroenVanHautte** [Redocly/developer-portal-starter#24]
Hi, thanks for adding the diagram title feature! I've tried it, but it seems arrowheads disappear from sequence diagrams on the second page - here's a code sample (same diagram code twice in a row - I've added spaces to prevent github from interpreting it as code in this issue description):
```
` ``mermaid X
sequenceDiagram
    participant A
    participant B
    A->>B: message
` ``
` ``mermaid Y
sequenceDiagram
    participant A
    participant B
    A->>B: message
` ``
```

Is there any way to prevent this?

**Comment by RomanHotsiy** [comment]
Hey @JeroenVanHautte,

That's weird... We have to investigate why this happens.

Thanks for the report!

**Comment by RomanHotsiy** [comment]
Hey @JeroenVanHautte,

We managed to find the root cause of the issue. We will be able to publish a fix it early next week.

**Comment by JeroenVanHautte** [comment]
Just checked again, this is working perfectly now!

**Comment by RomanHotsiy** [comment]
Oh! Thanks for the confirmation!
