### ISSUE TITLE
Feature Request: Customize toc

### ISSUE THREAD

**Issue by C4st3ll4n** [Redocly/developer-portal-starter#246]
I would like to translate the toc title "On this page" to Pt-BR, or any other language. like

```

toc:
  enable: true
  label: Tabela de conteúdo #Instead of "On this page"

```

**Comment by C4st3ll4n** [comment]
any updates ?

**Comment by RomanHotsiy** [comment]
Hey @C4st3ll4n.

Sorry for the delay. Our main communication channel about the premium products is support email.

Unfortunately, this functionality is not supported right now.

We'' have support for it and also a much more powerful i18n in our next-gen portal coming Q2 2023.

Thanks.
