### ISSUE TITLE
The build command fails with zero information on errors

### ISSUE THREAD

**Issue by aditya-docs** [Redocly/developer-portal-starter#249]
![image](https://user-images.githubusercontent.com/106972852/229364159-be4db424-5668-4a2a-a654-850f31a4c4ca.png)

We recently purchased the developer portal but need help running the build command. Almost always, the builds fail, and we could deploy the portal only once. The error messages need to include information on why the build failed. Here is an example above. ^^^ I Need a support person to set up a call to explain how we can make the portal builds a smooth process. 
Our org id is **tray-docs-gto**

**Comment by romanpryshliak** [comment]
Hi @aditya-docs,

Thank you for reaching out.

Upon reviewing the portal build, I can see that the cause of its failure is the following error:

```
error Bundled definition with errors at openapi/openapi.yaml.
```

This error means that the `openapi.yaml` OpenAPI definition file is not valid and, therefore, the portal build failed.

To avoid similar issues in the future, I would recommend conducting a local linting of your OpenAPI definition files prior to pushing changes to production.

To accomplish this task, you can use the Redocly CLI, which enables you to validate the OpenAPI definition files locally and identify errors. You can refer to the following links for more information:

https://redoc.ly/docs/cli/quickstart/
https://redoc.ly/docs/cli/installation/
https://redoc.ly/docs/cli/commands/lint/

If you have any further questions, please don't hesitate to contact us at team@redocly.com.
