### ISSUE TITLE
Doubt remove first page

### ISSUE THREAD

**Issue by mjossany** [Redocly/developer-portal-starter#252]
Is it possible to remove the first page generated by the index.mdx on root?

I would like to go direct to the index.md page on developer-portal lvl.

**Comment by Orest-Yastremskyy** [comment]
Hi @mjossany 
You can do so by removing the index.mdx page from the root of your developer portal and replace it with your index.md page (you can simply move it to the root). You would also need to adjust your sidebars.yaml file accordingly. Here is my example of doing so:

![image](https://github.com/Redocly/developer-portal-starter/assets/96121440/4ed0051f-6d28-45b1-8e48-4203b21e81c2)

**Comment by mjossany** [comment]
Thank you, @Orest-Yastremskyy!
