### ISSUE TITLE
Doubt change nav gradient color theme

### ISSUE THREAD

**Issue by mjossany** [Redocly/developer-portal-starter#253]
I want to use a gradient white to green (from left to right) on the nav bar on the top. I tried some changes to theme.ts but unsuccessfuly. Would you help me understand better how to set up theme.ts to get a gradient like I described?

**Comment by Orest-Yastremskyy** [comment]
Hi @mjossany 
You would need to use a `gradient` property in the theme.ts. Please, refer to the article below for detailed information:

https://redocly.com/docs/developer-portal/configuration/theme/
