### ISSUE TITLE
Deploying developer-portal-starter to Redocly

### ISSUE THREAD

**Issue by mjossany** [Redocly/developer-portal-starter#254]
Hi!

I finished the setup of my documentation portal with developer-portal-starter and deployed it to Redocly.

My portal is like the image below:
![image](https://github.com/Redocly/developer-portal-starter/assets/80066268/ca9e7efd-b74f-4cd4-9b73-aa518859b373)

However, when I deployed it to Redocly and clicked to visualize the API docs what I get is just the OpenAI definitions:
![image](https://github.com/Redocly/developer-portal-starter/assets/80066268/ef175466-164f-4543-83a6-6999d0229f0c)

Could you tell me what I need to do to deploy the portal on Redocly and make all the customizations, markdowns, etc be visible?

**Comment by Orest-Yastremskyy** [comment]
Hi @mjossany 

Is there a chance you could provide us with your email address and organization id?

You can also contact us directly via chat or email at redocly@redocly.com.

**Comment by mjossany** [comment]
Sure!

E-mail: mjossany@gmail.com
Organization name: Jossany

**Comment by mjossany** [comment]
Is it possible to test the deploy on Portals before upgrading to the Professional plan? Just to check how it works before asking the budget to it here on my team.

**Comment by Orest-Yastremskyy** [comment]
Kindly note, that the gatsby-based portal you inquired about is going to be discontinued. We do not intend to onboard any new customers to the portal at the moment.

We have a set of new products that will replace it and more, but they are in a private alpha release now and our current user cohort is full. The next availability may be in September but there is a waiting list.

Thank you for understanding.
