### ISSUE TITLE
Disable ToC if there is only one subheader

### ISSUE THREAD

**Issue by JeroenVanHautte** [Redocly/developer-portal-starter#26]
Currently, if there is only one subheader on a page, the table of contents is still shown on the right (if it is enabled globally) - however, in this situation there is no added value (and it is confusing to users). Would it be possible to allow this to be disabled per page or in the case where only a single subheader is present on the page?

**Comment by adamaltman** [comment]
You can disable the page TOC on a per-page basis if you want in the front-matter.

https://redoc.ly/docs/developer-portal/page-toc/

```
enableToc: false
```

**Comment by JeroenVanHautte** [comment]
Thanks @adamaltman!
