### ISSUE TITLE
Try it console styling bug in Firefox on small screens

### ISSUE THREAD

**Issue by JeroenVanHautte** [Redocly/developer-portal-starter#30]
On small screens in firefox (on Windows), the try it console looks like this:

![image](https://user-images.githubusercontent.com/11805125/94914749-e8684b80-04ab-11eb-935f-e397b092c494.png)

This can be resolved by changing the CSS style of one of the divs around it (from flex 1 1 0% to flex 1 1 auto):

![image](https://user-images.githubusercontent.com/11805125/94914811-02a22980-04ac-11eb-9f7f-533fd5095a84.png)

Could this be integrated into the next release?

**Comment by RomanHotsiy** [comment]
@JeroenVanHautte yes, we'll include it into the next release.

**Comment by RomanHotsiy** [comment]
This has been fixed in `@Redocly/developer-portal@beta.84`
