### ISSUE TITLE
Enterprise builds fail with "No space left on device"

### ISSUE THREAD

**Issue by dchisolm** [Redocly/developer-portal-starter#45]
We have a critical issue updating our documentation site using Enterprise builds. Earlier versions of our specifications were building fine, but after updating and re-adding a second specification to the portal, builds fail with the messages below using "@redocly/developer-portal": "1.0.0-beta.89". 

```9:28:15 AM: 
success onPostBuild - 73.553s
9:28:15 AM: 
warning The size of at least one page context chunk exceeded 500kb, which could lead to degraded performance. Consider putting less data in the page context.
9:28:16 AM: 
warning Error persisting state: ENOSPC: no space left on device, write
...
9:28:17 AM: 
Portal build failed
9:28:17 AM: 
Deploy failed: updating build status
```

I beleive this to be due to the size of the specifications, and I was able to reproduce the issue using publically available specifications for the GitHub API. Both specs in our case are registry links, but this also fails with local files.

Reproduction steps (using public specifications)

Copy two versions of the GitHub OpenAPI spec
https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.yaml

Add to siteConfig.yaml

```
oasDefinitions:
  g1: specifications/github-one.openapi.yaml
  g2: specifications/github-two.openapi.yaml
```

Both are defined as below in /openapi directory, with a config for each.

```type: redoc
definitionId: g2
showInfo: true
expand: true
settings:
  jsonSampleExpandLevel: 'all'
  expandResponses: '200'
  hideDownloadButton: true
  requiredPropsFirst: false
  sortPropsAlphabetically: false
  showExtensions: false
  showConsole: false
```

When committing this change, the build fails as described.

This issue is currently blocking progress for our team, so please reach out should you need help reproducing.

**Comment by RomanHotsiy** [comment]
Hey @dchisolm!

Thank you so much for reproduction! I can confirm that we can reproduce it on our end.

We're investigating it and we'll try to fix it ASAP.

**Comment by dchisolm** [comment]
Hi,

Thanks for the quick turnaround on this. Our last few builds have been successful! Awesome way to start a weekend!

**Comment by RomanHotsiy** [comment]
Thank you for the reproduction!
