### ISSUE TITLE
Sidebar training excercise has wrong example

### ISSUE THREAD

**Issue by MarcoDeJong** [Redocly/developer-portal-starter#7]
On the Sidebar training exercises page, the following text states:
```
Open the upgrade page in a new tab.
Notice it renders without any sidebar.
```

**Expected**
When I open the upgrade page in a new tab the page renders without any sidebar

**Actual**
When I open the upgrade page in a new tab the page renders with a sidebar

_Cause:_ 
The `sidebars.yaml` already contains a reference to `upgrade.md` on line 68

**Comment by adamaltman** [comment]
Thanks! I committed after I completed the exercises. I'll fix that.
