### ISSUE TITLE
issue in hosting with domain

### ISSUE THREAD

**Issue by kumaramc** [Redocly/developer-portal-starter#77]
We received trial enterprise license key for developer portal. After putting the license key in siteConfig.yaml and changing package.json - "scripts": {
    "start": "redocly-portal build -p 3000",
    "build": "redocly-portal build",
    "clean": "redocly-portal clean"
getting below error.

`There was an error in your GraphQL query:

request to https://api.redoc.ly/mermaid failed, reason: connect ECONNREFUSED 35.171.214.154:443

   1 | query MarkdownQuery($pageId: String!, $id: String!) {
   2 |   markdownRemark(fields: {contentId: {eq: $id}}) {
>  3 |     html
     |     ^
   4 |     headings {
   5 |       value
   6 |       depth
   7 |     }
   8 |   }
   9 |   contentItem(pageId: {eq: $pageId}) {
  10 |     fields {
  11 |       lastModified
  12 |     }
  13 |     data {

File path: D:/redoc_workarea/developer-portal-starter-master/node_modules/@redocly/developer-portal/dist/engine/src/templates/simple-markdown.js
Url path: /developer-portal/mermaid/
Plugin: none

success run page queries - 2.761s - 57/57 20.65/s`

Please let me know how to configure to host with domain name.

Thanks
Ram

**Comment by RomanHotsiy** [comment]
Hi @kumaramc, it may be related to some firewall on your end blocking requests to https://api.redoc.ly/mermaid.

I suspect it may be related to the `.ly` domain. Could you try the following:

```
set REDOCLY_MERMAID_MICROSERVICE_URL=https://api.redocly.com/mermaid
npm run build
```

**Comment by kumaramc** [comment]
Still getting the same issue. It is possible to switch off mermaid.


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

request to https://api.redocly.com/mermaid failed, reason: connect ECONNREFUSED 35.171.149.71:443

   1 | query MarkdownQuery($pageId: String!, $id: String!) {
   2 |   markdownRemark(fields: {contentId: {eq: $id}}) {
   3 |     html
>  4 |     headings {
     |     ^
   5 |       value
   6 |       depth
   7 |     }
   8 |   }
   9 |   contentItem(pageId: {eq: $pageId}) {
  10 |     fields {
  11 |       lastModified
  12 |     }
  13 |     data {
  14 |       enableToc

File path: D:/redoc_workarea/developer-portal-starter-master/node_modules/@redocly/developer-portal/dist/engine/src/templates/simple-markdown.js
Url path: /developer-portal/mermaid/
Plugin: none


 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

request to https://api.redocly.com/mermaid failed, reason: connect ECONNREFUSED 35.171.149.71:443

   1 | query MarkdownQuery($pageId: String!, $id: String!) {
   2 |   markdownRemark(fields: {contentId: {eq: $id}}) {
>  3 |     html
     |     ^
   4 |     headings {
   5 |       value
   6 |       depth
   7 |     }
   8 |   }
   9 |   contentItem(pageId: {eq: $pageId}) {
  10 |     fields {
  11 |       lastModified
  12 |     }
  13 |     data {

File path: D:/redoc_workarea/developer-portal-starter-master/node_modules/@redocly/developer-portal/dist/engine/src/templates/simple-markdown.js
Url path: /developer-portal/mermaid/
Plugin: none

not finished run page queries - 2.838s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The build is not completing due to the error. When curl on graphQL query url, getting error "{"message":"Missing Authentication Token"}"

Thanks
Ram

**Comment by RomanHotsiy** [comment]
@kumaramc yes, just remove the pages with mermaid diagrams in it, in your case looks like it's just one file:

`developer-portal/mermaid.md`

**Comment by kumaramc** [comment]
I am able to build and deploy the portal. Now using domain (as per license generated ) when i access /openapi/reference/overview/ page getting "Invalid license key: missing key. Please contact team@redoc.ly to remedy the problem." 

I am able to get the /openapi/reference/overview/ page when accessed using localhost.

Thanks
Ramkumar.C

**Comment by AntonKozachuk** [comment]
Hi @kumaramc, 
Could you please specify how you build the portal? 
Also, it might be helpful to know how you host it.
Your feedback will help us to investigate the issue.
Thanks in advance.

**Comment by kumaramc** [comment]
After the build executed using "yarn start" with code "start": "redocly-portal build  -p 3000", the public folder is created. The  public folder is hosted in nodejs server as web application using expressjs to render marked down/html files.

Thanks
Ramkumar.C

**Comment by RomanHotsiy** [comment]
Hey @kumaramc,

Is there a chance you can share the resulting bundle with us over email?
Are you on Windows/Linux/Max?

Could you please contact us in our support channel (team@redoc.ly or use built-in chat at app.redoc.ly)? We would like to set up a call to help us investigate the issue.

Thanks.

**Comment by kumaramc** [comment]
I am using Windows server to host the application.

Thanks
Ramkumar.C

**Comment by adamaltman** [comment]
We believe this is fixed in beta 134 (the master branch here is updated to beta 134). 

#80

**Comment by kumaramc** [comment]
After upgrade it works.
Thanks
Ramkumar.C
