### ISSUE TITLE
Markdownquery error

### ISSUE THREAD

**Issue by kumaramc** [Redocly/developer-portal-starter#79]
The version 1.0.0-beta.131 display following error when accessing http://localhost:3000/. Running in wndows server 2016 :-

ERROR #85910
Open in Editor
C:/redocly-workarea/developer-portal-starter-master/node_modules/@redocly/developer-portal/dist/engine/src/templates/simple-markdown.js
Multiple "root" queries found: "MarkdownQuery" and "MarkdownQuery".
Only the first ("MarkdownQuery") will be registered.

Instead of:

   1 | query MarkdownQuery {
   2 |   markdownRemark {
   3 |     #...
   4 |   }
   5 | }
   6 |
   7 | query MarkdownQuery {
   8 |   markdownRemark {
   9 |     #...
  10 |   }
  11 | }

Do:

  1 | query markdownQueryAndMarkdownQuery {
  2 |   markdownRemark {
  3 |     #...
  4 |   }
  5 |   markdownRemark {
  6 |     #...
  7 |   }
  8 | }

This can happen when you use two page/static queries in one file. Please combine those into one query.
If you're defining multiple components (each with a static query) in one file, you'll need to move each component to its own file.
See our docs page for more info on this error: https://www.gatsbyjs.org/docs/graphql/

Thanks
Ramkumar.C

**Comment by Marshevskyy** [comment]
Hi @kumaramc 
Unfortunately, I can not replicate it.
What nodejs version you use?
Could you try to upgrade Portal version from 1.0.0-beta.131 to version 1.0.0-beta.136.  Please let me know if you still see this error.

**Comment by kumaramc** [comment]
After upgrade it works. 
Thanks
Ramkumar.C
