### ISSUE TITLE
Make all (HTML) headers themeable

### ISSUE THREAD

**Issue by MarcoDeJong** [Redocly/developer-portal-starter#8]
Within Markdown the following headers are valid

```
# h1 Heading
## h2 Heading
### h3 Heading
#### h4 Heading
##### h5 Heading
###### h6 Heading
```
which results in 

# h1 Heading
###### h6 Heading

However in the `theme.ts` only option heading1 till heading3 are valid. Please make all headings themeable.

**Comment by RomanHotsiy** [comment]
We'll add heading4 heading6 to the theme.ts in the next portal release early next week.

Thanks for the suggestion!

**Comment by RomanHotsiy** [comment]
`1.0.0-beta.65` supports `heading4`, `heading5` and `heading6` typography configuration. It accepts same set of values that other headings.
