### ISSUE TITLE
theme.ts: Explain use of typography

### ISSUE THREAD

**Issue by MarcoDeJong** [Redocly/developer-portal-starter#9]
I am making great progress with branding the developer portal. Customisation of fonts, colours, etc. seems quite easy to understand and to implement. The devil is in the details however.

For example:
When I look at the rendered output of the links `<a>` in the footer, they seem to have a `font-weight:700`, which I didn't define anywhere. The `<a>` in the navigation has `font-weight:600` in turn. In `theme.ts` I only find a 'fontWeightBold'; however there is no pointing to where this is applicable in the rendered output.

Please be a bit more descriptive on where each property is being used.

**Comment by RomanHotsiy** [comment]
> Please be a bit more descriptive on where each property is being used.

Thanks for pointing it out. There is no 100% theme.ts coverage yet, unfortunately.

We will fix the issues you have in the next portal release early next week.

**Comment by RomanHotsiy** [comment]
This was a bug. Some `font-weight` values were just hardcoded.

`1.0.0-beta.65` now uses values from the theme.
